project:
  type: website

website:
  title: "Rflow"
  navbar:
    collapse-below: lg
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Tutorials"
        href: tutorials/index.qmd
      - text: "How-To"
        href: howto/index.qmd
      - text: "Fundamentals"
        href: fundamentals/index.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "About"
        href: about.qmd
    right:
      - text: "Login"
        href: https://rflow.co.uk/login
      - text: "Start for Free"
        href: https://rflow.co.uk/signup

  sidebar:
    - id: tutorials
      title: "Tutorials"
      style: "docked"
      background: light
      contents:
        - tutorials/

    - id: howto
      title: "How-To"
      contents:
        - howto/

    - id: fundamentals
      title: "Fundamentals"
      contents:
        - fundamentals/

    - id: reference
      title: "Reference"
      contents:
        - reference/index.qmd
        - reference/add-column.qmd
        - reference/barchart.qmd
        - reference/boxplot.qmd
        - reference/density.qmd
        - reference/diagnostics.qmd
        - reference/factor.qmd
        - reference/glm.qmd
        - reference/histogram.qmd
        - reference/input-csv.qmd
        - reference/linear-model.qmd
        - reference/mean-stats.qmd
        - reference/output-csv.qmd
        - reference/predict-lm.qmd
        - reference/residuals.qmd
        - reference/scatterplot.qmd
        - reference/summary-stats.qmd
        - reference/tukey-hsd.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-after-body: navbar-search-order.html
    toc: true



