---
title: "Tutorials"
---


Step-by-step tutorials for learning Rflow. ***In development***. More tutorials will be added over time.

:::{.columns}

::: {.column width="48%"}
<a href="tutorial_1a.qmd" class="click-box">
<span class="click-box-title">
Tutorial 1A: Basics of Rflow
</span>
This shows you how to create a simple Rflow workflow, import data, display summary tables and visualisations of your data, and save your workflow. You can either clone a pre-prepared copy of this tutorial, or build your own from scratch.
</a>
:::


::: {.column width="4%"}
<!-- Spacer column -->
:::

::: {.column width="48%"}
<a href="tutorial_1b.qmd" class="click-box">
  <span class="click-box-title">
  Tutorial 1B: Simple visualisation
  </span>
  This tutorial introduces you to a range of simple visualisation techniques, including scatterplots, line plots, and bar charts. You can either clone a pre-prepared copy of this tutorial, or build your own from scratch.
</a>
:::
:::

::: {.columns}
::: {.column width="48%"}
<a href="tutorial_1c.qmd" class="click-box">
  <span class="click-box-title">
  Tutorial 1C: Bar charts with error bars
  </span>
  Producing bar charts with error bars is a common task in many environmental and biological datasets. This tutorial shows you how to do this in Rflow. You can either clone a pre-prepared copy of this tutorial, or build your own from scratch.
</a>
:::

::: {.column width="4%"}
<!-- Spacer column -->
:::

::: {.column width="48%"}
<a href="tutorial_2.qmd" class="click-box">
  <span class="click-box-title">
  Tutorial 2: Introduction to linear models
  </span>
  This tutorial covers the basics of linear models, including simple and multiple regression. You can either clone a pre-prepared copy of this tutorial, or build your own from scratch.
</a>
:::

:::

::: {.clickable-feature-grid}
::: {.clickable-feature-card}
<a href="tutorial_1a.qmd" class="card-link">
  <h3>Tutorial 1A: Basics of Rflow</h3>
  
  This tutorial shows you how to create a simple Rflow workflow, import data, display summary tables and visualisations of your data, and save your workflow.
  </a>
:::

::: {.clickable-feature-card}
<a href="tutorial_1b.qmd" class="card-link">
  <h3>Tutorial 1B: Simple visualisation</h3>

  This tutorial introduces you to a range of simple visualisation techniques, including scatterplots, line plots, and bar charts.
  </a>
:::

::: {.clickable-feature-card}
<a href="tutorial_1c.qmd" class="card-link">
  <h3>Tutorial 1C: Bar charts with error bars</h3>
  
  Producing bar charts with error bars is a common task in many environmental and biological datasets. This tutorial shows you how to do this in Rflow.
</a>

:::

::: {.clickable-feature-card}
<a href="tutorial_2.qmd" class="card-link">
  <h3>Tutorial 2: Introduction to linear models</h3>

  This tutorial covers the basics of linear models, including simple and multiple regression. It shows you how to interpret the results of these models and check their validity.
</a>
::: 

:::
